author: Erik Vullings
version: 0.0.1
menus:
  - id: cyber
    title: Cyber analysis
    logo: ""
    description: GUI for cyber analysts supporting a mission
    menuGroups:
      - id: city
        title: City
        description: City related web-sites and services
      - id: power
        title: Electricity network
        description: Hacks related to manipulating the power grid
      - id: security
        title: Security services
        description: Security hacks
    menuItems:
      - id: city.hr
        groupId: city
        title: Access the personnel files
        description: Access the personnel files so you can find out about certain people.
      - id: power.grid
        groupId: power
        title: Access the Power Grid
      - id: power.lights_off
        groupId: power
        title: Switch off the street lights
        isVisible: false
        actions: power.lights_off
        conditions:
          - eventId: power.grid
          - eventId: event.power_on
      - id: power.lights_on
        groupId: power
        title: Switch on the street lights
        isVisible: false
        actions: power.lights_on
        conditions:
          - eventId: event.power_off
      - id: power.lights_auto
        groupId: power
        title: Switch street lights to auto
        isVisible: false
        actions: power.lights_auto
        multiple: -1
        conditions:
          - eventId: power.grid
      - id: security.access
        groupId: security
        title: Get access to the local network
        actions: security.hack_network
      - id: security.camera_off
        groupId: security
        title: Switch off the security cameras
        isVisible: false
        multiple: -1
        actions: security.camera_off
        conditions:
          - eventId: event.local_network_hack_on
          - eventId: event.camera_on
      - id: security.camera_on
        groupId: security
        title: Switch on the security cameras
        isVisible: false
        multiple: -1
        actions: security.camera_on
        conditions:
          - eventId: event.camera_off
  - id: social_media
    title: Social media analysis
    description: GUI for social media analysts supporting a mission
    menuGroups:
      - id: global
        title: Mood analysis
        description: Determine the mood towards you
      - id: personal
        title: Personal analysis
        description: Analysing specific people
    menuItems:
      - id: global.scan
        groupId: global
        title: Perform mood scan
        actions: global.scan
      - id: personal.principal
        groupId: personal
        title: Investigate principal of facility
        isVisible: false
        actions: personal.principal
        conditions:
          - eventId: city.hr
      - id: personal.prisonguard
        groupId: personal
        title: Investigate prison guard of facility
        isVisible: false
        actions: personal.prisonguard
        conditions:
          - eventId: city.hr

actions:
  - id: security.hack_network
    description: Hack the local network
    timeout: 10
    result:
      message:
        response: Local network is being hacked
        group: PrisonNetwork
        type: ON
      event:
        response: Local network is hacked
        status: SUCCEEDED
        eventId: event.local_network_hack_on
  - id: security.camera_off
    description: Switch the security camera off
    timeout: 10
    result:
      message:
        response: Security camera is being switched off
        group: Camera
        type: OFF
      event:
        status: SUCCEEDED
        response: Security camera is switched off
        eventId: event.camera_off
  - id: security.camera_on
    description: Switch the security camera on
    timeout: 100
    result:
      message:
        response: Security camera is being switched on
        group: Camera
        type: ON
      event:
        status: SUCCEEDED
        response: Security camera switched on
        eventId: event.camera_on
  - id: power.lights_off
    description: Switch the street lights in VBS3 off
    timeout: 10
    result:
      message:
        response: Lights are being switched off
        group: MnhznAll
        type: OFF
      event:
        response: Lights are switched off
        status: SUCCEEDED
        eventId: event.power_off
  - id: power.lights_on
    description: Switch the street lights in VBS3 on
    timeout: 10
    result:
      message:
        response: Lights are being switched off
        group: MnhznAll
        type: ON
      event:
        response: Lights are switched off
        status: SUCCEEDED
        eventId: event.power_on
  - id: power.lights_auto
    description: Switch the street lights in VBS3 to auto mode
    timeout: 10
    result:
      message:
        response: Lights are being switched to auto mode
        group: MnhznAll
        type: Auto
      event:
        response: Lights are switched to auto mode
        status: SUCCEEDED
        eventId: event.power_auto
